import './globals.css'
import Model from '@/components/Model'

export const metadata = {
  title: 'Trello 2.0 by AKHILESH',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6F8]'>{children}
        <Model />
      </body>
    </html>
  )
}
